name: Test Performance Workflow

on:
  workflow_dispatch: # Allow manual trigger for testing

permissions:
  contents: read
  pull-requests: write
  actions: read

jobs:
  test-performance:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run CI performance check
      run: npm run ci:performance
      
    - name: Check if performance report exists
      run: |
        if [ -f "performance-budget-report.json" ]; then
          echo "✅ Performance report generated successfully"
          cat performance-budget-report.json | jq '.'
        else
          echo "❌ Performance report not found"
          exit 1
        fi